import { CommonSonner } from "@/components/common/CommonSonner";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import FrontMenuLayout from "./layout/frontmenu";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={geist.variable}>
      <body className="flex flex-col min-h-screen bg-slate-50 font-sans">
        <main className="flex-1 container mx-auto p-4 md:p-8">
          {children}
        </main>
        <CommonSonner />
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};